trigger:
  branches:
    include:
      - master
      - develop
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'production'

steps:
- task: UseNode@1
  inputs:
    version: '22.x'

- script: |
    npm install
    npx expo export --platform web # Ajuste a plataforma conforme necessário
  displayName: 'Instalar dependências e build do projeto'

- script: |
    npm test
  displayName: 'Executar testes unitários e de integração'

- script: |
    "build": "expo build:android" 
  displayName: 'Executar testes unitários e de integração'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud' # Substitua pelo nome da conexão do SonarCloud
    organization: 'kelvinfernandess04' # Substitua pelo nome da organização no SonarCloud
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'kelvinfernandess04_SoloQuest' # Substitua pela chave do projeto no SonarCloud
    cliProjectName: 'SoloQuest'
    cliSources: '.' # Ajuste o caminho do código-fonte, se necessário

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'